### ISSUE TITLE
Largo listas input 

### ISSUE THREAD

**Issue by javiprado** [IIC2115/Syllabus#89]
Hola!
Me gustaría saber con qué largo de listas probar los programas para evaluar su eficiencia y que no se demoren más de 1 segundo, ya que claramente si le pongo una lista gigante, va a sobrepasar el segundo.
Gracias!

**Comment by halobel** [comment]
En general, debiese bastar en el rango 1000-10000, dependiendo del problema. Seguramente probaremos con listas más grandes, pero en ese caso la regla de un segundo será adecuada al problema.

**Comment by simonerenard** [comment]
@halobel Profesor una pregunta, en el problema 1, el código me corre en menos de un segundo para listas de tamaño 1.000 pero ya para listas de tamaño 10.000 me aparece el siguiente error:

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

¿Debo preocuparme de este error y hacer que mi código funcione obligatoriamente para una lista de 10.000 elementos o con los 1.000 elementos esta bien?

**Comment by mblejeune** [comment]
@halobel  y para el problema 2 en específico la lista máxima que se especifica en el enunciado de 10^5 ¿también debería durar máximo 1 segundo ? o lo de 1 segundo sería para casos entre 10^3-10^4 en esta pregunta, gracias!

**Comment by halobel** [comment]
Hola, voy a responder acá a ambas preguntas. Con respecto a la primera, demorarse menos de 1 segundo en una lista de 10^3 está bien, es suficiente para ese ejercicio, y para 10^4, entre 5s y 10s suena razonable. El error que te sale, se debe a que (creo) estás imprimiendo algo en pantalla mientras haces los cálculos. Imprimir en pantalla es lejos lo más lento que se puede hacer, por lo que te recomiendo que no lo hagas dentro de la función que soluciona el problema, sino que fuera de ella, de manera que el tiempo de ejecución no lo tome en cuenta. Además de que si tu código se cae con listas de tamaño 10^4, no podremos evaluarlo en esos casos y no tendrías el puntaje asociado.
Con respecto a la segunda pregunta, entre 1s y 1,5s la diferencia no es mucha, y podría explicarse incluso por un computador  rápido, por lo que es razonable como solución.

**Comment by FelipeUlloan** [comment]
profe dado su respuesta anterior, 
Cuál sería el largo suficiente de la lista para el problema 3 donde debe seguir arrojando un tiempo de ejecución de 1 segundo?
Saludos!
